;;; ggstow/manifest.scm — Export link plan in various formats
;;;
;;; Currently supports:
;;;   - Guix Home home-files-service-type alist (export-guix)

(define-module (ggstow manifest)
  #:export (plan->guix-alist
            write-guix-alist))

(define (plan->guix-alist plan)
  "Convert a plan (list of <link>) to a Guix Home files alist.
   Returns: '((\"relative/path\" . (local-file \"/abs/source\")) ...)"
  (map (lambda (link)
         (let* ((home   (getenv "HOME"))
                (target (link-target link))
                (source (link-source link))
                ;; Strip $HOME/ prefix for relative target path
                (rel    (if (string-prefix? (string-append home "/") target)
                            (substring target (+ 1 (string-length home)))
                            target)))
           (list rel source)))
       plan))

(define (write-guix-alist alist port)
  "Write ALIST as a Guix Home home-files-service-type snippet to PORT."
  (display ";; Generated by ggstow export-guix\n" port)
  (display ";; Add to your home-configuration.scm:\n" port)
  (display ";;\n" port)
  (display ";; (simple-service 'ggstow-files\n" port)
  (display ";;                 home-files-service-type\n" port)
  (display ";;                 `(\n" port)
  (for-each
   (lambda (entry)
     (format port ";;    (~s ,(local-file ~s))\n"
             (car entry) (cadr entry)))
   alist)
  (display ";;   ))\n" port))
